### ISSUE TITLE
Option to implement the time-filters in subreddit scraper

### ISSUE THREAD

**Issue by Stochastic13** [JosephLai241/URS#14]
Since the PRAW's `praw.models.Subreddit.top` allows the option of a time filter (select one of the following: _all, day, hour, month, week, year_, with _all_ being the default), can we have this additional optional option following the `-r` flag, something like `-r subreddit_name [H|N|C|T|R|S] num_posts top_category`?

**Comment by JosephLai241** [comment]
Thank you for the enhancement suggestion! 

I am currently looking into implementing Pushshift's API over PRAW for certain parts of URS since there are [features that are not possible with PRAW](https://github.com/JosephLai241/Universal-Reddit-Scraper/issues/13). 

PRAW's `Subreddit` model also offers the time filter for `controversial` and `search`, so I will see about adding the time filter option for those categories as well when I get around to the Pushshift refactor.

Stay tuned for updates!
