### ISSUE TITLE
Invalid Grant error processing request

### ISSUE THREAD

**Issue by braddaking** [JosephLai241/URS#28]
There is nothing wrong with my API credentials.
However whenever I run Urs.py -r vizards N 100
the program says that my API credentials are not right and give me that error.
I know my API credentials are right and tested them on another piece of code. What could be creating this error?

**Comment by JosephLai241** [comment]
It looks like you just joined GitHub so you might not be familiar with how bug report templates work. For future reference, **do not delete the default issue template that is loaded when you create a new issue in a repository**. Its purpose is to maintain a structured, detailed set of information so that it is possible for developers to replicate the bug that you are describing.

Please revise your bug report by filling out the default template.

**Comment by jamesrichter** [comment]
I had the same thing happen to me.  I had to change 

            username = os.getenv("USERNAME"),

to 

            username = os.getenv("REDDIT_USERNAME"),


and to REDDIT_USERNAME in the config file as well.
Because in windows there is already a "username" environment variable which overrode the value in my config file.

**Comment by JosephLai241** [comment]
@jamesrichter thank you for bringing this to my attention. I was not aware Windows already has a `username` environment variable. I will amend the corresponding scripts so that Windows users will not run into this issue again.
