### ISSUE TITLE
Unable to run Urs.py

### ISSUE THREAD

**Issue by noah-hu** [JosephLai241/URS#29]
When attempting to run Urs.py I receive the following error.
`noah@noahdesktop ~/S/U/urs> ./Urs.py -h`
`Traceback (most recent call last):`
` File "/home/noah/Scrapers/URS-master/urs/./Urs.py", line 30, in <module>`
`    from urs.utils.Logger import LogMain`
`ModuleNotFoundError: No module named 'urs'`

**Machine Specs**
* OS: [e.g. Arch Linux x86_64]
* Python: [e.g. Python 3.8.2]
* PRAW: [e.g. PRAW 7.0.0]

**Additional Context**
I am unsure if this is due to my own error or not. I am relatively new to python.

**Comment by JosephLai241** [comment]
While you did not correctly fill out the bug report, I do appreciate how you included the traceback of the error. I had forgotten to update the install command in the main `README` as it is now outdated. That being said, I believe the issue may be resolved by running `pip install` within the `URS` directory:

```
git clone https://github.com/JosephLai241/URS.git
cd URS/
pip install . -r requirements.txt
```

For future reference, **please do not delete or modify the default issue template when you open an issue within an open-source repository**. Its purpose is to maintain a structured, detailed set of information so that it is possible for developers to replicate the bug that you are describing.

**Comment by torrentx** [comment]
For me that command doesn't work from the urs directory. End up getting Directory '.' is not installable.

**Comment by sdubaifanchuan** [comment]
You should run setup.py first.

**Comment by JosephLai241** [comment]
My apologies for the late response. After doing some research, it seems the issue could be related to your `PYTHONPATH`. Try running this line within your shell:
 
```
python3 -c "import os, sys; print(os.environ['PYTHONPATH']); print(sys.path) if 'PYTHONPATH' in sorted(os.environ) else print('PYTHONPATH is not defined')"
```

Running the command will print a list containing directories where Python will look for modules. If your `PYTHONPATH` is not set, it will print "PYTHONPATH is not defined".

If the path to where URS is saved on your machine is not in the list, try adding it to `PYTHONPATH`. [Here is a link that explains how to do so for each operating system](https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html#setting-pythonpath-more-permanently).

**Comment by Af7eR9l0W** [comment]
^ Note above. I was getting PYTHONPATH error, it wasnt even adding the 'not defined' part. I manage to fix both that, and the missing urs module by just running `python3 setup.py install` Then ran the pip requirements again just to be safe. Followed by running Urs.py in the root directory like `python3 ./urs/Urs.py`
