### ISSUE TITLE
[Enhancement Request] None of the endpoints seem to return the gallery images, can those be gotten?

### ISSUE THREAD

**Issue by vesper8** [JosephLai241/URS#34]
**Describe The Bug**

I'm scraping a subreddit that is heavy on images, each post often has 1-12 images added in a gallery format. Neither the subreddit endpoint or the comments endpoint seem to be returning data on those images. While it would be nice if the images could be downloaded, a simple list of image urls in json format would be greatly appreciated

**Expected Behavior**

```
python3 ./urs/Urs.py -r cats h 100
```

Returns many posts including this one: https://www.reddit.com/r/cats/comments/niiwmx/my_new_bff/

That post has a gallery of 5 images

```
python3 ./urs/Urs.py -c https://www.reddit.com/r/cats/comments/niiwmx/my_new_bff/ 0
```

I would expect either of the above queries to return data for those 5 images.. the url of the gallery itself is returned but not of the images themselves

**Actual Behavior**

URLs of the images in the gallery are nowhere to be found

URL of gallery is returned however: https://www.reddit.com/gallery/niiwmx

Is it possible to add an endpoint to fetch the data from galleries such as the one above?

**Machine Specs**

* OS: [Big Sur]
* Python: [3.7]

**Additional Context**

N/A

**Comment by vesper8** [comment]
Hrm so after digging a bit on redditdev

It seems that previoulsy praw would return a "preview" key that would include this image data

And thanks to one of the comments here https://www.reddit.com/r/redditdev/comments/ms4ic7/how_do_i_get_gallery_content/

It seems that getting the json I'm after is as simple as replacing `gallery` with `comments` and appending `.json`

So `https://www.reddit.com/gallery/niiwmx` becomes `https://www.reddit.com/comments/niiwmx.json`

And voila!

It would be very nice if this trick could be implement in URS so that the gallery data could be included when using it

**Comment by JosephLai241** [comment]
Thank you for taking the time to fill out the Bug Report template as well as providing additional information from your own research. I will definitely consider the information you have provided during development.

This would actually be categorized as an enhancement request rather than a bug. As of v3.2.1, I have not implemented code to extract gallery data from submissions. The data returned from the Subreddit and submission comments scrapers are as expected.

I am currently working on v3.3.0 and will see to adding this feature to the release. Off the top of my head, I have some ideas as to how I can implement this:

* Something like `Urs.py -g|--gallery https://www.reddit.com/gallery/niiwmx`
* Including gallery data in the `submission_metadata` dictionary after running the submission comments scraper
* Possibly both ideas

I need to do some more research before finalizing anything, so stay tuned for updates!

**Comment by vesper8** [comment]
Loving your new enhancements @JosephLai241 ! When do you think you'll be tagging 3.3.0?

**Comment by JosephLai241** [comment]
Thank you @vesper8! I will tag the new version after I record a GIF for the new livestream tools and do one more check for the source code and Markdown files. Recording GIFs is arguably the most cumbersome aspect in making this repository user-friendly, but I believe it should be finished sometime this weekend 👍🏻
