### ISSUE TITLE
Fix setup.py encoding

### ISSUE THREAD

**Issue by 1011025m** [JosephLai241/URS#38]
I run on Windows 10 and my system language is not English, it probably uses big5 instead.

I get this error every time I try to update and setup a new build
`Traceback (most recent call last):
  File "E:\Py\URS-3.3.0\setup.py", line 20, in <module>
    LONG_DESCRIPTION = readme.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 7935: illegal multibyte sequence`

You can probably fix it by setting the encoding when the file is loading. I didn't want to open a pull request because I don't want a fork for this tiny issue.

Thanks

**Comment by JosephLai241** [comment]
I have specified encoding within `setup.py`, which should fix your installation issues.

Additionally, there are two things I want to mention:

1) **Please do not delete the preset issue template when opening a new issue**. There are many reasons why developers take the time to create these skeletons, the most important is to get all the necessary information from users so that we can quickly address issues. Fortunately in this case you have provided enough information here as well as a traceback, so I was able to fix the issue you described. However, please keep this in mind when opening new issues in the future.
2) You can always delete your fork after it is merged into the `master` branch. You do not have to keep it indefinitely.
